[project]
name = "example"
version = "0.1.0"
description = "Example project for pixi-kernel"
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64"]

[dependencies]
python = "3.11.*"
bash_kernel = "*"
ipykernel = "*"
r-irkernel = "*"
xeus-cling = "*"
